version: '3.2'

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=todo-api
      - POSTGRES_USER=todo-api
      - POSTGRES_PASSWORD=123

volumes:
  db: